// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function ConnectWebSocket():Promise<void>;

export function DisconnectWebSocket():Promise<void>;

export function FindAllUsers():Promise<services.APIResponse_ui_services_FindAllUsersResponse_>;

export function GetUserRooms():Promise<services.APIResponse_ui_services_GetUserRoomsResponse_>;

export function Login(arg1:services.LoginRequest):Promise<services.APIResponse_ui_services_LoginResponse_>;

export function Register(arg1:services.RegisterRequest):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
