// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWebSocket() {
  return window['go']['services']['HTTPClientService']['ConnectWebSocket']();
}

export function DisconnectWebSocket() {
  return window['go']['services']['HTTPClientService']['DisconnectWebSocket']();
}

export function FindAllUsers() {
  return window['go']['services']['HTTPClientService']['FindAllUsers']();
}

export function Login(arg1) {
  return window['go']['services']['HTTPClientService']['Login'](arg1);
}

export function Register(arg1) {
  return window['go']['services']['HTTPClientService']['Register'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['HTTPClientService']['Startup'](arg1);
}
